// Automatically generated by make_default_presets.py

#define PRESET_NAMES {"Arsenate", "C14", "Carbon Dioxide", "Carbon Monoxide", "Crust", "Cyanide", "Default", "Exotic Metals 1", "Free Radical", "Halogens 1", "Halogens 2", "Hydrochloric Acid", "Hydrofluoric Acid", "Isotonic", "Light Metals 1", "Meltdown", "Methane", "Nitrate", "Noble Metals", "N-Type", "Phosphate", "P-Type", "Radon Leak", "Rare Earth Chimes", "Rare Earth Echo", "Reductant", "Red Earth", "Spontaneous Decay", "Water", "White Paint", "Xenon Hexafluoride"}

constexpr char* PRESET_ID_LIST[]{"Arsenate", "C14", "Carbon_Dioxide", "Carbon_Monoxide", "Crust", "Cyanide", "Default", "Exotic_Metals_1", "Free_Radical", "Halogens_1", "Halogens_2", "Hydrochloric_Acid", "Hydrofluoric_Acid", "Isotonic", "Light_Metals_1", "Meltdown", "Methane", "Nitrate", "Noble_Metals", "N_Type", "Phosphate", "P_Type", "Radon_Leak", "Rare_Earth_Chimes", "Rare_Earth_Echo", "Reductant", "Red_Earth", "Spontaneous_Decay", "Water", "White_Paint", "Xenon_Hexafluoride"};

constexpr wchar_t* PRESET_ID_LIST_W[]{L"Arsenate", L"C14", L"Carbon_Dioxide", L"Carbon_Monoxide", L"Crust", L"Cyanide", L"Default", L"Exotic_Metals_1", L"Free_Radical", L"Halogens_1", L"Halogens_2", L"Hydrochloric_Acid", L"Hydrofluoric_Acid", L"Isotonic", L"Light_Metals_1", L"Meltdown", L"Methane", L"Nitrate", L"Noble_Metals", L"N_Type", L"Phosphate", L"P_Type", L"Radon_Leak", L"Rare_Earth_Chimes", L"Rare_Earth_Echo", L"Reductant", L"Red_Earth", L"Spontaneous_Decay", L"Water", L"White_Paint", L"Xenon_Hexafluoride"};

constexpr int N_PRESETS = 31;
